### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by zl22good** [jterrace/ha-reolink-rich-notifications#1]
Attempted to use this Blueprint with the Android Home Assistant Companion app. 

The notification is missing the photo. I've attempted to fix with no luck.

**Comment by jterrace** [comment]
This was working pretty well for me up until I stopped using it because I sold my Reolink cameras. They're super overhyped imo, I ended up ditching them for Tapo cameras.

But I can still try to help you get it working. Have you looked at traces of the automation? When you open up the automation, there's a Traces button on top right where you can then click through to see what it did. Any errors in there?

Do you see any images in your `/media/reolink_rich_notifications/` directory from the terminal in home assistant?

**Comment by zl22good** [comment]
Thanks for the speedy response. The images are not being saved properly. I'm looking into this as the original blueprint works but I liked the delay part you added.

**Comment by jterrace** [comment]
It's using the `camera.snapshot` action (https://www.home-assistant.io/integrations/camera/#action-snapshot) with `/media`. Is the snapshot call failing?

**Comment by zl22good** [comment]
Home assistant isn't showing this service call as failing.

**Comment by jterrace** [comment]
Can you try going to Developer Tools -> Actions and see if it works when you manually call it there?

![image](https://github.com/user-attachments/assets/995d8e2e-84be-48c9-b0d9-6abad93717ea)

**Comment by zl22good** [comment]
I tried this -
![image](https://github.com/user-attachments/assets/e3d84d0e-8fdc-4aa1-bdb8-e67166c3f796)

and it get this when I ssh into the docker container 
![image](https://github.com/user-attachments/assets/2c5947c9-e2ae-41f1-a0e9-c0c5c8102ec9)

**Comment by jterrace** [comment]
I'm guessing you're not using home assistant OS? I wonder if it needs to change to `/media/local` based on reading https://www.home-assistant.io/integrations/media_source/

But I think maybe in your terminal, you're looking in the host OS /media, not the /media inside the docker container. Can you enter the ha container and look at /media?

**Comment by zl22good** [comment]
Thank you, this is the first HA automation I've worked on. I was able to get it working in docker with the following.
![image](https://github.com/user-attachments/assets/06f55254-b106-4e24-860f-1daad5de1e51)

**Comment by jterrace** [comment]
Hmm that looks like the public url:
https://companion.home-assistant.io/docs/notifications/notification-attachments/#www-folder

It's nicer to use the media source instead, I wonder why that didn't work for you.
